Allow overriding of components on command line and quoting of parameters
git-svn-id: svn://svn.riscos.info/gccsdk/trunk@6854 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/autobuilder/develop/git/setvars b/autobuilder/develop/git/setvars
--- a/autobuilder/develop/git/setvars
+++ b/autobuilder/develop/git/setvars
@@ -1,7 +1,5 @@
-echo "ERROR: **** AUTOBUILDER ERROR *****" 1>&2
-echo "ERROR: This port of git is currently broken due to filename issues" 1>&2
-echo "ERROR: Remove this error in autobuilder/develop/git/setvars to build anyway" 1>&2
-exit 1
+echo "WARNING: **** AUTOBUILDER ERROR *****" 1>&2
+echo "WARNING: This port of git is currently broken due to filename issues" 1>&2
 
 # Make function
 #
@@ -18,19 +16,10 @@ ab_make () {
 	$GCCSDK_INSTALL_ENV/ro-make NO_NSEC=YesPlease NO_PREAD=Yes
 }
 
-# Package function
-#
-# You will need to define this to do your packaging for RiscPkg. 
-# There are several variables to use here:
-# $S build directory
-# $D top level of destination package directory
-# $H autobuilder directory for package
-# $A RISC OS application (after calling ab_create_app, etc)
-#
-#ab_package () {
-#   ab_create_app MyApp Apps/Graphics     # !MyApp will be copied from $H, and the package section will be Graphics
-#   ab_add_commands $S/myapp${AB_EXEEXT}  # For applications containing command line utilities, this adds aliases to !Boot 
+ab_package () {
+   ab_create_command_app Git Development/Git
+   ab_add_commands $S/*${AB_EXEEXT}
 
-#   $AB_HOME/add-riscpkg -unixlib         # Last step to complete packaging
-#}
+   $AB_HOME/add-riscpkg -unixlib         # Last step to complete packaging
+}
 
