* porting-scripts/ro-config: The grep used to find the correct position to insert RISC OS into the linking and versioning characteristics of the configure script can fail on newer versions of configure. Such versions of configure are likely to have been generated by autoreconf and the addition of support for new targets means that "gnu*)" is no longer at the end of a line causing the grep failure. This results in shared libraries not being built. If the grep does fail, then use a perl script to patch configure. * porting-scripts/patch-configure.pl: Patch configure so that it is aware of the RISC OS dynamic linker. We do this by looking for occurrences of "rdos*)" and inserting the relevant details for RISC OS.
git-svn-id: svn://svn.riscos.info/gccsdk/trunk@6501 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/gcc4/porting-scripts/ro-config b/gcc4/porting-scripts/ro-config
--- a/gcc4/porting-scripts/ro-config
+++ b/gcc4/porting-scripts/ro-config
@@ -45,6 +45,20 @@ adde1f() {
   if grep -q -- "^gnu\*)" $e1fPATH ; then
     echo RISC OS: Adding libtool handling
     sed -i "s#^gnu\*)#gnu\* | riscos\*)#" $e1fPATH
+  else
+    # The above grep can fail on later versions of configure (perhaps regenerated after
+    # using autoreconf) where other targets have been added and gnu* is no longer the first
+    # thing on the line.
+    # Only do this once.
+    if ! grep -q -- "^riscos\*)" $e1fPATH ; then
+      echo "RISC OS: Failed to patch configure to support libtool."
+      echo "RISC OS: This may be because configure was regenerated by autoreconf."
+      echo "RISC OS: Calling perl script to patch configure instead."
+      mv -f $e1fPATH $e1fPATH.old
+      GCCSDK_ENV/patch-configure.pl $e1fPATH $e1fPATH.old
+      rm -f $e1fPATH.old
+      chmod 755 $e1fPATH
+    fi
   fi
 
   # Use CX11
