Check for native compiler first
git-svn-id: svn://svn.riscos.info/gccsdk/trunk@3976 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/autobuilder/develop/vala/setvars b/autobuilder/develop/vala/setvars
--- a/autobuilder/develop/vala/setvars
+++ b/autobuilder/develop/vala/setvars
@@ -3,6 +3,11 @@ AB_MAINTAINER="Jan-Jaap van der Geer <jjvdgeer@c2i.net>"
 AB_LICENCE="Free"
 AB_ROVERSION=0
 
+if ! which valac > /dev/null; then
+  echo "Native valac required"
+  exit 1
+fi
+
 ab_package() {
   valadir=$D/Apps/Development
   mkdir -p $valadir
