Fix download script so it doesn't exit early
git-svn-id: svn://svn.riscos.info/gccsdk/trunk@2755 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/gcc4/download-gcc-binutils b/gcc4/download-gcc-binutils
--- a/gcc4/download-gcc-binutils
+++ b/gcc4/download-gcc-binutils
@@ -31,7 +31,7 @@ if [ "x"$1 = "xgcc" ] ; then
   fi
   # Download gcc
   echo +++ Downloading gcc $GCCSDK_SUPPORTED_GCC_RELEASE
-  wget -q -O $GCCSDK_GCCORIG-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2 http://ftp.gnu.org/gnu/gcc/gcc-$GCCSDK_SUPPORTED_GCC_RELEASE/gcc-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2 || echo "Failed to download" && exit 1
+  wget -q -O $GCCSDK_GCCORIG-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2 http://ftp.gnu.org/gnu/gcc/gcc-$GCCSDK_SUPPORTED_GCC_RELEASE/gcc-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2 || (echo "Failed to download" && exit 1) || exit 1
   echo +++ Unpacking gcc $GCCSDK_SUPPORTED_GCC_RELEASE
   tar xjf $GCCSDK_GCCORIG-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2
   mv gcc-$GCCSDK_SUPPORTED_GCC_RELEASE $GCCSDK_GCCORIG
@@ -45,7 +45,7 @@ else
   fi
   # Download binutils
   echo +++ Downloading binutils $GCCSDK_SUPPORTED_BINUTILS_RELEASE
-  wget -q -O $GCCSDK_BINUTILSORIG-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2 http://ftp.gnu.org/gnu/binutils/binutils-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2 || echo "Failed to download" && exit 1
+  wget -q -O $GCCSDK_BINUTILSORIG-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2 http://ftp.gnu.org/gnu/binutils/binutils-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2 || (echo "Failed to download" && exit 1) || exit 1
   echo +++ Unpacking binutils $GCCSDK_SUPPORTED_BINUTILS_RELEASE
   tar xjf $GCCSDK_BINUTILSORIG-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2
   mv binutils-$GCCSDK_SUPPORTED_BINUTILS_RELEASE $GCCSDK_BINUTILSORIG
