Add support for dependencies
git-svn-id: svn://svn.riscos.info/gccsdk/trunk@1660 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/autobuilder/build b/autobuilder/build
--- a/autobuilder/build
+++ b/autobuilder/build
@@ -5,6 +5,7 @@ AB_DEBUG=no           # Leave source
 AB_PACKONLY=no        # Zip only from current directory
 AB_NOFETCH=no         # Using existing source fetched from last time
 AB_VERBOSE=no         # Echo output
+AB_DEPS=yes           # Build dependencies first
 
 for param in $@ ; do
   case "$param" in
@@ -19,6 +20,9 @@ for param in $@ ; do
        ;;
     -v)
        AB_VERBOSE=yes
+       ;;
+    -n)
+       AB_DEPS=no
        ;;
     -*)
        echo "Autobuilder: unknown option $param"
@@ -69,7 +73,7 @@ AB_TMPDIR=$PWD
 # Change to autobuilder home
 if [ "$AB_PACKONLY" != "yes" ] ; then
  cd $AB_HOME
-fi  
+fi
 
 # If a specific package is named, build that; otherwise everything
 if [ "$AB_PACKAGES" == "" ] ; then
@@ -83,44 +87,102 @@ fi
 #rm -f /tmp/ab-success
 #rm -f /tmp/ab-failure
 
-for AB_PACKAGEDIR in $AB_PACKAGES ; do
- AB_PACKAGE=$(echo "$AB_PACKAGEDIR" | sed -e "s#/\$##" -e "s#/#\n#g" | tail -1)
+if [ "$AB_VERBOSE" == "yes" ] ; then
+  AB_STDOUT=/dev/stdout
+else
+  AB_STDOUT=/dev/null
+fi
 
- if [ -d $AB_HOME/$AB_PACKAGEDIR ] ; then
+ab_build() {
 
-   if [ -e $AB_HOME/$AB_PACKAGEDIR/setvars ] ; then
-     if [ "$AB_VERBOSE" == "yes" ] ; then
-       AB_STDOUT=/dev/stdout
-     else
-       AB_STDOUT=/dev/null
-     fi
+  local PACKAGE_NAME=$1
+  local IS_DEPENDENCY=$2
 
-     $AB_HOME/build-program 2>&1 | tee /tmp/ab-output >$AB_STDOUT
+  # Because the dependency info only contains the package name, and not the
+  # directory, we need to search for the directory containing this package.
+  local PACKAGE_DIR=`(cd $AB_HOME ; echo */$PACKAGE_NAME/setvars)`
+  if [ ! -e "$AB_HOME/$PACKAGE_DIR" ] ; then
+    PACKAGE_DIR=`(cd $AB_HOME ; echo */*/$PACKAGE_NAME/setvars)`
+  fi
+  PACKAGE_DIR=`dirname $PACKAGE_DIR`
 
-     if ! grep "Autobuilder - package completed" < /tmp/ab-output >/dev/null ; then
-       echo "Package $AB_PACKAGE: ***Failure***"
-       #cat /tmp/ab-output >> /tmp/ab-failure
-       mv /tmp/ab-output $AB_HOME/$AB_PACKAGEDIR/last-failure
-     else
-       echo "Package $AB_PACKAGE: Success"
-       #cat /tmp/ab-output >> /tmp/ab-success
+  if [ "$AB_DEPS" == "yes" ] ; then
 
-       if ! grep "Autobuilder - Running make install" > /dev/null < /tmp/ab-output   && \
-            grep "Autobuilder: No files specified to package" > /dev/null < /tmp/ab-output ; then
-         echo "Warning: not installed, and not packaged"
-       fi
+    local DEPENDENCIES
+    local DEP
 
-       mv /tmp/ab-output $AB_HOME/$AB_PACKAGEDIR/last-success
-       rm -f $AB_HOME/$AB_PACKAGEDIR/last-failure
-     fi
-     echo
-   else
-     echo "Autobuilder: No setvars found for package \"$AB_PACKAGE\" - ignoring" 1>&2
-   fi
-   #rm -f /tmp/ab-success /tmp/ab-failure
- else
-   if ! [ -e "$AB_HOME/$AB_PACKAGEDIR" ] ; then
-     echo "Autobuilder: No directory found for package \"$AB_PACKAGE\" - ignoring" 1>&2
-   fi  
- fi
+    if [ "`which apt-cache`" != "" ] ; then
+      DEPENDENCIES=`apt-cache depends $PACKAGE_NAME | grep Depends: | sed 's/^.*Depends: //'`
+    fi
+
+    if [ -e "$AB_HOME/$PACKAGE_DIR/depends" ] ; then
+      DEPENDENCIES=`echo $DEPENDENCIES | cat $AB_HOME/$PACKAGE_DIR/depends`
+    fi
+
+
+    for DEP in $DEPENDENCIES ; do
+      # Filter out libc6 as it isn't needed and seems to have a circular dependency
+      if ! (echo "$DEP" | grep libc6 > /dev/null) ; then
+        if ! ab_build $DEP 1 ; then
+          return 1
+        fi
+      fi
+    done
+  fi
+
+
+  # If we get here then all dependencies for this package should be satisfied.
+  AB_PACKAGE=$PACKAGE_NAME
+  AB_PACKAGEDIR=$PACKAGE_DIR
+
+  if [ "$IS_DEPENDENCY" == "1" ] ; then
+    if [ -e "$AB_HOME/$AB_PACKAGEDIR/last-success" ] ; then
+      echo "Autobuilder - Dependency $AB_PACKAGE satisfied"
+      return 0
+    fi
+  fi
+
+  if [ -d $AB_HOME/$AB_PACKAGEDIR ] ; then
+
+    if [ -e $AB_HOME/$AB_PACKAGEDIR/setvars ] ; then
+      $AB_HOME/build-program 2>&1 | tee /tmp/ab-output >$AB_STDOUT
+      #echo  foo  > /tmp/ab-output
+
+      if ! grep "Autobuilder - package completed" < /tmp/ab-output >/dev/null ; then
+        echo "Package $AB_PACKAGE: ***Failure***"
+        #cat /tmp/ab-output >> /tmp/ab-failure
+        mv /tmp/ab-output $AB_HOME/$AB_PACKAGEDIR/last-failure
+        return 1
+      else
+        echo "Package $AB_PACKAGE: Success"
+        #cat /tmp/ab-output >> /tmp/ab-success
+
+        if ! grep "Autobuilder - Running make install" > /dev/null < /tmp/ab-output   && \
+             grep "Autobuilder: No files specified to package" > /dev/null < /tmp/ab-output ; then
+          echo "Warning: not installed, and not packaged"
+        fi
+
+        mv /tmp/ab-output $AB_HOME/$AB_PACKAGEDIR/last-success
+        rm -f $AB_HOME/$AB_PACKAGEDIR/last-failure
+      fi
+      echo
+
+    else
+      echo "Autobuilder: No setvars found for package \"$AB_PACKAGE\" - ignoring" 1>&2
+    fi
+    #rm -f /tmp/ab-success /tmp/ab-failure
+  else
+    if ! [ -e "$AB_HOME/$AB_PACKAGEDIR" ] ; then
+      echo "Autobuilder: No directory found for package \"$AB_PACKAGE\" - ignoring" 1>&2
+    fi
+  fi
+
+  return 0
+}
+
+for PACKAGEDIR in $AB_PACKAGES ; do
+ PACKAGE=$(echo "$PACKAGEDIR" | sed -e "s#/\$##" -e "s#/#\n#g" | tail -1)
+
+ ab_build $PACKAGE 0
+
 done
