Add some slightly complex logic for package name vs preprocess.
The idea is to retain the legacy behaviour, but also allow preprocess
to work where the archive unpackages to multiple directories, and
we can't immediately determine a package name.



git-svn-id: svn://svn.riscos.info/gccsdk/trunk@4474 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/autobuilder/build-program b/autobuilder/build-program
--- a/autobuilder/build-program
+++ b/autobuilder/build-program
@@ -314,15 +314,27 @@ if true; then
   AB_FULLNAME=$(find . -mindepth 1 -maxdepth 1 -type d | grep -v unpack | grep -v package | cut -b 3-)
 
   if [ "$(wc -w <<<$AB_FULLNAME)" != "1" ] ; then
-    echo "Autobuilder: Could not determine package name.  Found \"$AB_FULLNAME\"" 1>&2
-    exit 1
+    if ! [ -e $AB_HOME/$AB_PACKAGEDIR/preprocess ] ; then
+      echo "Autobuilder: Could not determine package name.  Found \"$AB_FULLNAME\"" 1>&2
+      exit 1
+    fi
+    unset AB_FULLNAME
   fi
 
   # Run any preprocess script to unpack it in any special way
   if [ -e $AB_HOME/$AB_PACKAGEDIR/preprocess ] ; then
-    cd $AB_FULLNAME
+    if [ -n "$AB_FULLNAME" ] ; then cd $AB_FULLNAME; fi
     echo "Autobuilder: Calling preprocess"
     . $AB_HOME/$AB_PACKAGEDIR/preprocess
+
+    if [ -n "$AB_FULLNAME" ] ; then
+      AB_FULLNAME=$(find . -mindepth 1 -maxdepth 1 -type d | grep -v unpack | grep -v package | cut -b 3-)
+
+      if [ "$(wc -w <<<$AB_FULLNAME)" != "1" ] ; then
+        echo "Autobuilder: Could not determine package name.  Found \"$AB_FULLNAME\"" 1>&2
+        exit 1
+      fi
+    fi
 
   # Check to see if it's tarred up inside
   elif [ -d "$AB_FULLNAME/upstream" ] ; then
