Patches mentioned in the list sometimes have an extension
git-svn-id: svn://svn.riscos.info/gccsdk/trunk@4412 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/autobuilder/build-program b/autobuilder/build-program
--- a/autobuilder/build-program
+++ b/autobuilder/build-program
@@ -377,6 +377,16 @@ if true; then
     for AB_PATCH in $patches; do
       echo "Autobuilder: Debian patch: $AB_PATCH"
       AB_PATCH=debian/patches/$AB_PATCH
+
+      if ! [ -e $AB_PATCH ] ; then
+        AB_PATCH=$AB_PATCH.dpatch
+
+        if ! [ -e $AB_PATCH ] ; then
+          echo "Autobuilder: Patch \"$AB_PATCH\" not found" 1>&2
+          exit 1
+        fi
+      fi
+
       # Not all patches are at the same level. Do some heuristic (see simple-patchsys.mk).
       AB_PATCH_SUCCESS=""
       for AB_PATCH_LEVEL in 0 1 2 ; do
