polkit-policy-file-validate is unavailable on Ubuntu, as there was no outcome as to whether it's necessary any more in a thread last year.  Since it's only used in Vala AFAIK, I've turned lack of it into a warning rather than an error
Patch from Theo Markettos <theo@markettos.org.uk>


git-svn-id: svn://svn.riscos.info/gccsdk/trunk@5475 5d7976f4-0b0e-0410-a586-d2bac8e3be52

diff --git a/autobuilder/build b/autobuilder/build
--- a/autobuilder/build
+++ b/autobuilder/build
@@ -73,10 +73,15 @@ check_dependencies() {
        popd
     fi
   fi
-  for build_prog in cvs svn wget autoconf automake rman realpath pkg-config doxygen xgettext unzip autoconf2.13 flex bison gperf glib-genmarshal xsltproc intltoolize automake-1.7 polkit-policy-file-validate ; do
+  for build_prog in cvs svn wget autoconf automake rman realpath pkg-config doxygen xgettext unzip autoconf2.13 flex bison gperf glib-genmarshal xsltproc intltoolize automake-1.7 ; do
     if ! type $build_prog > /dev/null 2>&1 ; then
       echo "Autobuilder: $build_prog not found; is it installed on your path?"
       exit 1;
+    fi
+  done
+  for build_prog in polkit-policy-file-validate ; do
+    if ! type $build_prog  > /dev/null 2>&1 ; then
+      echo "Autobuilder warning: $build_prog not found; continuing anyway"
     fi
   done
 }
